name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Dart SDK
      uses: dart-lang/setup-dart@v1.0

    - name: Install dependencies
      run: dart pub get

    - name: Run tests
      run: dart test
